---
docker:
  image: "g4s8/rultor:alpine"
env:
  MAVEN_OPTS: "-Xmx1g"
merge:
  script:
    - "mvn install -B -Pqulice,itcase"
    - "pdd --source=$(pwd) --verbose --file=/dev/null"
  fast-forward: "no"
architect:
  - "g4s8"
