---
docker:
  image: "g4s8/rultor:alpine"
env:
  MAVEN_OPTS: "-Xmx1g"
merge:
  script:
    - mvn install -B -Pqulice
    - pdd --source=$(pwd) --verbose --file=/dev/null
    - gitlint --subject-regex='#\d+ - .*'
  fast-forward: "no"
architect:
  - "g4s8"
