---
version: 2
jobs:
  build:
    docker:
      - image: g4s8/rultor:alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: mvn-install
          command: mvn install -Pqulice
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: validate-commits
          command: gitlint --subject-regex="#\d+ - .*"
      - run:
          name: validate-puzzles
          command: pdd --source=$(pwd) --verbose --file=/dev/null
