---
version: 2
jobs:
  build:
    # @todo #52:30min Change CircleCI configuration to use machine instead of Docker,
    #  in order to enable execution of Testcontainers.
    #  See https://www.testcontainers.org/supported_docker_environment/continuous_integration/circle_ci/
    docker:
      - image: g4s8/rultor:alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn install -Pqulice
      - run: pdd --source=$(pwd) --verbose --file=/dev/null
