---
version: 2
jobs:
  build:
    docker:
      - image: g4s8/rultor:alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn install -Pqulice,itcase
      - run: pdd --source=$(pwd) --verbose --file=/dev/null
